"""
Lipi Snap — Synthetic Word Image Generator (Clean Only) - For training and testing (manually)
"""

import csv, random
from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw, ImageFont

# --- Paths ---
PROJECT_ROOT = Path(__file__).resolve().parent.parent
# We use the clean list generated by your split script
WORDS_FILE   = PROJECT_ROOT / "data" / "new_test_words_clean.txt"
OUTPUT_DIR   = PROJECT_ROOT / "data" / "test_synthetic_words" / "images"
LABELS_FILE  = PROJECT_ROOT / "data" / "test_synthetic_words" / "labels.csv"

# --- Configuration ---
TEST_MODE       = False
TEST_WORD_COUNT = 20

FONT_PATHS = {
    "nithya": PROJECT_ROOT / "font" / "NithyaRanjanaDU-Regular.otf",
    "nlg":    PROJECT_ROOT / "font" / "ranjana_NLG_v3_fixed.ttf",
}

IMAGE_H, IMAGE_W = 64, 512
FONT_SIZE = 96
H_MARGIN, W_MARGIN = 6, 8
BG_COLOR, FG_COLOR = 0, 255

def load_font(path, size):
    path = str(path)
    try:
        return ImageFont.truetype(path, size, layout_engine=ImageFont.Layout.RAQM)
    except (AttributeError, Exception):
        try: return ImageFont.truetype(path, size)
        except Exception as e:
            print(f"❌ Font failed: {path}: {e}")
            return None

def render_word(word, font):
    canvas = Image.new("L", (4000, 600), color=BG_COLOR)
    draw   = ImageDraw.Draw(canvas)
    try:
        draw.text((200, 200), word, font=font, fill=FG_COLOR, language="nep", direction="ltr")
    except (KeyError, Exception):
        canvas = Image.new("L", (4000, 600), color=BG_COLOR)
        draw   = ImageDraw.Draw(canvas)
        draw.text((200, 200), word, font=font, fill=FG_COLOR)

    bbox = canvas.getbbox()
    if not bbox: return None
    cropped = canvas.crop(bbox)

    glyph_h = IMAGE_H - 2 * H_MARGIN
    scale   = glyph_h / cropped.height
    new_w   = max(1, int(cropped.width * scale))

    max_w = IMAGE_W - 2 * W_MARGIN
    if new_w > max_w:
        scale   = max_w / cropped.width
        new_w   = max_w
        glyph_h = max(1, int(cropped.height * scale))

    resized = cropped.resize((new_w, glyph_h), resample=Image.Resampling.LANCZOS)
    final_img = Image.new("L", (IMAGE_W, IMAGE_H), color=BG_COLOR)
    y_off     = (IMAGE_H - resized.height) // 2
    final_img.paste(resized, (W_MARGIN, y_off))
    return final_img

def generate():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    if not WORDS_FILE.exists():
        print(f"❌ {WORDS_FILE} not found. Please run split_words script first.")
        return

    with open(WORDS_FILE, "r", encoding="utf-8") as f:
        words = [w.strip() for w in f if w.strip()]

    if TEST_MODE:
        words = words[:TEST_WORD_COUNT]
        print(f"🛠️  TEST_MODE: generating {TEST_WORD_COUNT} word-based samples.")

    fonts = {name: load_font(path, FONT_SIZE) for name, path in FONT_PATHS.items()}
    print(f"🚀 Generating CLEAN images for {len(words)} words...")

    counter = 1
    with open(LABELS_FILE, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["filename", "label"])
        
        for idx, word in enumerate(words):
            for font_name, font_obj in fonts.items():
                if font_obj is None: continue
                base_img = render_word(word, font_obj)
                if base_img is None: continue
                
                # Simple, clean filename
                fname = f"{counter:06d}_{font_name}.png"
                base_img.save(str(OUTPUT_DIR / fname))
                writer.writerow([fname, word])
                counter += 1

            if (idx + 1) % 1000 == 0:
                print(f"  Processed {idx+1}/{len(words)} words ({counter-1} images)")

    print(f"✅ Done! Total: {counter-1} clean images saved.")

if __name__ == "__main__":
    generate()
